name: 'Teamwork Github Sync'
description: 'This action helps you to sync your PRs with tasks in Teamwork to streamline team collaboration and your development workflows.'
branding:
  icon: 'alert-circle'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TEAMWORK_URI:
    description: 'Teamwork URI'
    required: true
  TEAMWORK_API_TOKEN:
    description: 'Teamwork API token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.TEAMWORK_URI }}
    - ${{ inputs.TEAMWORK_API_TOKEN }}
